djangotutorialredo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('pollsredo.urls'))
]

pollsredo/urls.py
from django.urls import path
from . import views

app_name = 'pollsredo'

urlpatterns = [
    path('', views.PollsIndexView.as_view(), name='polls'),
    path('<int:pk>/', views.PollsDetailsView.as_view(), name='details'),
    path('<int:pk>/results/', views.PollsResultsView.as_view(), name='results'),
    path('<int:pk>/vote', views.vote, name='vote')
]

pollsredo/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    text = models.CharField(max_length=100)
    publish_date = models.DateTimeField('publish date')

    def __str__(self):
        return self.text

    def recently_published(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.publish_date and self.publish_date < now

    recently_published.admin_order_field = 'pub_date'
    recently_published.boolean = True
    recently_published.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    num_votes = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.text

pollsredo/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.db.models import F

# Create your views here.

class PollsIndexView(generic.ListView):
    model = Question
    template_name = 'pollsredo/polls.html'

    def get_queryset(self):
        return Question.objects.order_by('-publish_date')[:5]

class PollsDetailsView(generic.DetailView):
    model = Question
    template_name = 'pollsredo/details.html'

    #get_queryset

class PollsResultsView(generic.DetailView):
    model = Question
    template_name = 'pollsredo/results.html'

def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)

    try:
        choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'pollsredo/details.html', {
            'question': question,
            'error': 'There was an error processing the request'
        })

    else:
        choice.num_votes = F('num_votes') + 1
        choice.save()

        return HttpResponseRedirect(reverse('pollsredo:results', args=(pk,)))

pollsredo/templates/pollsredo/details.html
{% if error %}
  <h2>{{ error }}</h2>
{% endif %}

{% if question %}
  <h2>{{ question.text }}</h2>
  <form class="" action="{% url 'pollsredo:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
      <label for="">
        <input type="radio" name="choice" value="{{ choice.id }}">
        {{ choice.text }}
      </label>
      <br>
    {% endfor %}
    <button type="submit" name="submit">Submit</button>
  </form>
{% endif %}

pollsredo/templates/pollsredo/polls.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pollsredo/style.css' %}">

{% if question_list %}
  <h2>List of questions</h2>
  <ol class="questions">
    {% for question in question_list %}
      <li>
        <span>{{ question.text }}</span> <a href="{% url 'pollsredo:details' question.id %}">Vote</a>
      </li>
    {% endfor %}
  </ol>
{% endif %}

pollsredo/templates/pollsredo/results.html
{% if question %}
  <h2>{{ question.text }}</h2>
  <ul>
    {% for choice in question.choice_set.all %}
      <li>
        {{ choice.text }} - {{ choice.num_votes }} vote{{ choice.num_votes|pluralize }}
      </li>
    {% endfor %}
  </ul>

<a href="{% url 'pollsredo:polls' %}">Vote again</a>
{% endif %}